export const ACTION_CREATE_CONTACT = 'CREATE_CONTACT';
export const ACTION_EDIT_CONTACT = 'EDIT_CONTACT';
export const ACTION_DELETE_CONTACT = 'DELETE_CONTACT';
export const ACTION_CHANGE_EDIT_MODE = 'CHANGE_EDIT_MODE';